### ISSUE TITLE
search bar returns 404 error

### ISSUE THREAD

**Issue by shandiya** [AtlasOfLivingAustralia/galah-R#206] opened 2023-09-12 00:32 UTC
Using the search bar in the top right corner of the vignette (https://galah.ala.org.au/R/) returns a 404 error.

**Comment by daxkellie** [comment] 2023-10-13 03:01
I think this was caused by pointing to the new R/Python landing page within `DESCRIPTION`. This should be fixed in commit bf0a8c7347e5a8d585fe2f295eb5e7e0c88bf23e

**Comment by daxkellie** [comment] 2023-11-27 04:31
Actually fixed in commit https://github.com/AtlasOfLivingAustralia/galah-R/commit/aec0acd58d96403838e602726efcc8c5d28185b9

**Closed by daxkellie** 2023-11-27 04:31 UTC
Labels: bug
